name: Meditation Magick
favicon: null
layout_spectrum: 0.19750111224129796
typography_spectrum: 0.04097883985377848
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#eef0d8'
    - '#22272a'
    - '#c5b756'
    - '#4a5252'
    - '#cf0e25'
  brandStrength: 0.7407101104035974
  lightness: 0.8125
  saturation: 0.625
  rhythmicContrast: 0.75
purpose: []
