name: Meditation Magick
favicon: null
layout_spectrum: 0.19750111224129796
typography_spectrum: 0.04097883985377848
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#211f20'
    - '#c2922e'
    - '#4f4d4e'
    - '#d5d3d4'
  brandStrength: 0.7407101104035974
  lightness: 0.9656410356983542
  saturation: 0.6426116398070008
  rhythmicContrast: 0.49949384783394635
purpose: []
